### ISSUE TITLE
Rf modules

### ISSUE THREAD

**Issue by ekber48** [xairy/hardware-village#1]
Hello, thanks for the detailed explanation about badusbs.Are you planing to do this on Modules that related to radio frequency (Hackrf and etc).And also rfid,nfc based controllers.And also please add some techniques about network explonation over a kernel.I have done pretty decent amount of network poisoning but they all are getting patched up.Thanks

**Comment by ekber48** [comment]
Over kernel i mean lan turtle,Raspberry pi

**Comment by xairy** [comment]
Hi! No plans for that just yet, maybe in the future. Thanks!
